### ISSUE TITLE
Set nvim as editor

### ISSUE THREAD

**Issue by peglah** [derekzyl/termux-nvim#1]
Neovim should be added as the default editor in Termux.

```
mkdir ~/bin
ln -s /data/data/com.termux/files/usr/bin/nvim ~/bin/termux-file-editor
```

**Comment by derekzyl** [comment]
What added advantage does it give?

**Comment by peglah** [comment]
You can choose to open files in Termux in Android. Then the file will be passed as an argument to the script/symlink in ~/bin/termux-file-editor, seemlessly opening the file in Neovim.

**Comment by derekzyl** [comment]
okay then l will add that to the script thanks

**Comment by derekzyl** [comment]
I have made this change but  I gave the user the option to decide if its what they would want or not
